services:
  web:
    image: dxwatch
    logging:
      driver: syslog
    environment:
      TZ: Asia/Tokyo
    build:
      context: .
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  import:
    image: dxwatch
    logging:
      driver: syslog
    volumes:
      - ./data:/app/data
    entrypoint: ["uv", "run", "python"]
    command: ["/app/import_dxpedition.py"]
    restart: "no"

  export:
    image: dxwatch
    logging:
      driver: syslog
    volumes:
      - ./data:/app/data
    entrypoint: ["uv", "run", "python"]
    command: ["/app/export_dxpedition.py"]
    restart: "no"
