services:
  app:
    image: spkreporter
    logging:
      driver: syslog
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./data:/app/data
    ports:
      - "80:8000"
    restart: unless-stopped
